allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - "@typescript-eslint/eslint-plugin@8.64.1-alpha.11"
  - "@typescript-eslint/parser@8.64.1-alpha.11"
  - "@typescript-eslint/project-service@8.64.1-alpha.11"
  - "@typescript-eslint/scope-manager@8.64.1-alpha.11"
  - "@typescript-eslint/tsconfig-utils@8.64.1-alpha.11"
  - "@typescript-eslint/type-utils@8.64.1-alpha.11"
  - "@typescript-eslint/types@8.64.1-alpha.11"
  - "@typescript-eslint/typescript-estree@8.64.1-alpha.11"
  - "@typescript-eslint/utils@8.64.1-alpha.11"
  - "@typescript-eslint/visitor-keys@8.64.1-alpha.11"
  - typescript-eslint@8.64.1-alpha.11
