export const ErrorCodes = {
  COMMON_BAD_REQUEST: "COMMON_BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  MISSING_HEADER: "MISSING_HEADER",

  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  TOKEN_MISMATCH: "TOKEN_MISMATCH",
  SIGNUP_EMAIL_MISMATCH: "SIGNUP_EMAIL_MISMATCH",
  INVALID_USER: "INVALID_USER",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  DUPLICATE_NICKNAME: "DUPLICATE_NICKNAME",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_VERIFIED_EMAIL: "DUPLICATE_VERIFIED_EMAIL",
  EMAIL_USED_BY_OTHER_ACCOUNT: "EMAIL_USED_BY_OTHER_ACCOUNT",
  USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  EMAIL_VERIFICATION_NOT_FOUND: "EMAIL_VERIFICATION_NOT_FOUND",
  EMAIL_CODE_MISMATCH: "EMAIL_CODE_MISMATCH",
  EMAIL_CODE_EXPIRED: "EMAIL_CODE_EXPIRED",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  NOT_UNIVERSITY_EMAIL: "NOT_UNIVERSITY_EMAIL",
  UNIVERSITY_NOT_FOUND: "UNIVERSITY_NOT_FOUND",

  STACK_NOT_FOUND: "STACK_NOT_FOUND",
  STACK_ALREADY_EXISTS: "STACK_ALREADY_EXISTS",

  UNIVERSITY_NOT_MATCHED: "UNIVERSITY_NOT_MATCHED",

  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  RECRUITMENT_EMPTY: "RECRUITMENT_EMPTY",
  PROJECT_DELETED: "PROJECT_DELETED",
  PROJECT_ALREADY_DELETED: "PROJECT_ALREADY_DELETED",
  AUTHOR_MISMATCHED: "AUTHOR_MISMATCHED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
